# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Victoria O'Dell
email: victoria.d.odell@gmail.com
description: Hey, I'm Victoria. I'm a graphic designer in Austin, Texas. I have interest and experience in UX/UI, interactive design, and branding. Curretly, I work at Continuum Analytics. I strive to make spaces diverse, inclusive, and empowering. Through good design and advocacy I hope to facilitate positive and progressive change. When I'm not designing you can find me on Slack, at An Instameet , or critiquing various pizza and salsas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: victoria_odell
github_username:  victoriaodell

# Build settings
markdown: kramdown
